### ISSUE TITLE
Check sass linter rules

### ISSUE THREAD

**Issue by mrhyde** [LotusTM/Kotsu#42]
Currently sass linter fail builds due huge amount of errors. We should check both code and rules to ensure that they fits our code style.

**Comment by ArmorDarks** [comment]
So far all tests will pass, but there still some linters that were disabled due to different reasons (all of them described in comments of `.scss-lint.yml`)

Related issues:
* https://github.com/brigade/scss-lint/issues/618
* https://github.com/brigade/scss-lint/issues/617
* https://github.com/brigade/scss-lint/issues/615
* https://github.com/brigade/scss-lint/issues/608

**Comment by ArmorDarks** [comment]
No longer actual due to #57 being implemented.
