### ISSUE TITLE
Replace `marked`

### ISSUE THREAD

**Issue by mrhyde** [LotusTM/Kotsu#56]
Since `marked` has not been updated for 7 months it's reasonable to take a look at more active alternatives (e.g. [markdown-it](https://github.com/markdown-it/markdown-it)) the question is - would it work with `nunjucks-markdown`?

**Comment by ArmorDarks** [comment]
Yes, we definitely have to replace it. I will look later for possible candidates. So far markdown-it looks good.

It should work with `nunjucks-markdown`, since the last one only parses Nunjucks templates and determinates which exactly portion of content should be passed to markdown formatter and returned back, nothing more.
